### ISSUE TITLE
Alfresco-share spring dependencies

### ISSUE THREAD

**Issue by narkuss** [Alfresco/share#113]
Hi all,

Alfresco share claims to use java11, but spring dependencies in original share image are not updated to support this. 
So, when we try to use spring annotations within a share project compiled with java11, share container fails at context initialization, due to version compatibility issues.
We must build share project using java8 in order to use spring annotations, while platform can be built using java11, because platform original image does have spring dependencies updated to support java11.

**Comment by montgolfiere** [comment]
FYI: https://issues.alfresco.com/jira/browse/SHA-2363

**Comment by narkuss** [comment]
Well, actually, I closed the issue because I realized that share does not claim to use java 11, but it's nice to see it will.
Thanks
