### ISSUE TITLE
The JARs config are loaded after the main config

### ISSUE THREAD

**Issue by alucas** [Alfresco/share#47]
https://github.com/Alfresco/share/blob/935f4b632b84b9ba09e1838b180c2a8acc1a897c/share/src/main/resources/alfresco/slingshot-application-context.xml#L55

Why ? Shouldn't the main config be load in last ?
If I create an addon with a custom config, then it can't be overided by the global config ?
Is there a special reason ? Doen't it need a comment to explain that non obvious beahaviour ?

**Comment by derekhulley** [comment]
This pattern is in use generally in Alfresco: the core configuration is correct and then overridden by custom configuration.

**Comment by alucas** [comment]
https://github.com/Alfresco/share/blob/935f4b632b84b9ba09e1838b180c2a8acc1a897c/share/src/main/resources/alfresco/slingshot-application-context.xml#L54

Is the core configuration ? I thought it was the global file where the server admin has to put his own config ?

**Comment by AFaust** [comment]
@alucas Note that there is already https://issues.alfresco.com/jira/browse/ALF-21820
